[railway]
volume = "/data"

[build]
builder = "NIXPACKS"

[[services]]
name = "backend"
dockerfile = "backend/Dockerfile"
watch_patterns = ["backend/**"]
port = 5000
healthcheck = "/"
envGenerationMode = "lookup"

[[services]]
name = "frontend"
dockerfile = "frontend/Dockerfile"
watch_patterns = ["frontend/**"]
port = 3000
healthcheck = "/"
